### ISSUE TITLE
Cannot run `make` from within the _elf_diff_ repo

### ISSUE THREAD

**Issue by sdettmer** [CapeLeidokos/elf_diff#29]
The README.md tells in `## Setup`

The following procedure is required to setup _elf_diff_.

> 1. Install Python version >= 3.0
> 2. Clone the [_elf_diff_](https://github.com/CapeLeidokos/elf_diff) repo from github.
> 3. Run `make` from within the _elf_diff_ repo or directly install required packages via pip as `pip install -r requirements.txt`

but I fail in step 3:

```
$ git clone https://github.com/CapeLeidokos/elf_diff
$ cd elf_diff
$ git remote -v
origin  https://github.com/CapeLeidokos/elf_diff (fetch)
origin  https://github.com/CapeLeidokos/elf_diff (push)
$ make
make: *** No targets specified and no makefile found.  Stop.
$ pip install -r requirements.txt
-bash: pip: command not found
$ python3 --version
Python 3.5.3
$ cat /etc/*release
PRETTY_NAME="Devuan GNU/Linux ascii"
NAME="Devuan GNU/Linux"
ID=devuan 
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"
```

What do I wrongly?

**Comment by noseglasses** [comment]
There was an error in the documentation. I had removed the makefile to have less dependencies.
I updated the README accordingly.
@sdettmer, `python3 -m pip install requirements.txt` should work for your Linux system as step 3.

**Comment by noseglasses** [comment]
Update: elf_diff now provides an official python package on PyPI.

To install on a Linux system do the following
```
python3 -m pip install elf_diff
```

The README was updated accordingly, now assuming an installed elf_diff Python package in all examples provided.

Closing this for now. Please feel free to reopen if any problems remain.
